"""postgresql initial

Revision ID: 20260805_0001
Revises:
Create Date: 2026-08-05 15:03:38.448955

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260805_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


OSTYPE = postgresql.ENUM("LINUX", "WINDOWS", name="ostype", create_type=False)
SCANTRIGGER = postgresql.ENUM(
    "MANUAL", "SCHEDULED", "IMPORT", "BATCH", name="scantrigger", create_type=False
)
SCANSTATUS = postgresql.ENUM("RUNNING", "SUCCESS", "FAILED", name="scanstatus", create_type=False)
SCANTASKSTATUS = postgresql.ENUM(
    "PENDING",
    "RUNNING",
    "SUCCESS",
    "FAILED",
    "CANCELLED",
    name="scantaskstatus",
    create_type=False,
)
SCANBATCHSTATUS = postgresql.ENUM(
    "PENDING", "RUNNING", "COMPLETED", name="scanbatchstatus", create_type=False
)
SCANBATCHTYPE = postgresql.ENUM(
    "ALL", "CLUSTER", "IMPORT", "RETRY", name="scanbatchtype", create_type=False
)
IMPORTBATCHSTATUS = postgresql.ENUM(
    "IMPORTING", "TESTING", "COMPLETED", "FAILED", name="importbatchstatus", create_type=False
)
IMPORTSTATUS = postgresql.ENUM(
    "IMPORTED", "SKIPPED", "ERROR", name="importstatus", create_type=False
)
IMPORTTESTSTATUS = postgresql.ENUM(
    "PENDING",
    "RUNNING",
    "SUCCESS",
    "FAILED",
    "NOT_APPLICABLE",
    name="importteststatus",
    create_type=False,
)

ENUM_TYPES = (
    OSTYPE,
    SCANTRIGGER,
    SCANSTATUS,
    SCANTASKSTATUS,
    SCANBATCHSTATUS,
    SCANBATCHTYPE,
    IMPORTBATCHSTATUS,
    IMPORTSTATUS,
    IMPORTTESTSTATUS,
)


def upgrade() -> None:
    """Upgrade schema."""
    for enum_type in ENUM_TYPES:
        enum_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("history_retention_days", sa.Integer(), nullable=True),
        sa.Column("scan_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("scheduled_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clusters_name"), "clusters", ["name"], unique=True)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("status", IMPORTBATCHSTATUS, nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("imported_rows", sa.Integer(), nullable=False),
        sa.Column("skipped_rows", sa.Integer(), nullable=False),
        sa.Column("error_rows", sa.Integer(), nullable=False),
        sa.Column("test_pending_rows", sa.Integer(), nullable=False),
        sa.Column("test_running_rows", sa.Integer(), nullable=False),
        sa.Column("test_success_rows", sa.Integer(), nullable=False),
        sa.Column("test_failed_rows", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fatal_error", sa.String(length=500), nullable=True),
        sa.Column("scan_batch_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_batches_scan_batch_id"), "import_batches", ["scan_batch_id"], unique=False
    )
    op.create_index(op.f("ix_import_batches_status"), "import_batches", ["status"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_retention_days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cluster_internal_networks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("cidr", sa.String(length=18), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id", "cidr", name="uq_cluster_internal_network_cluster_cidr"),
    )
    op.create_index(
        op.f("ix_cluster_internal_networks_cluster_id"),
        "cluster_internal_networks",
        ["cluster_id"],
        unique=False,
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("os_type", OSTYPE, nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("encrypted_password", sa.Text(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("scan_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("scheduled_enabled", sa.Boolean(), nullable=False),
        sa.Column("collection_enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("history_retention_days", sa.Integer(), nullable=True),
        sa.Column("last_scan_status", SCANSTATUS, nullable=True),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host", "port", "username", name="uq_device_identity"),
    )
    op.create_index(op.f("ix_devices_cluster_id"), "devices", ["cluster_id"], unique=False)
    op.create_table(
        "scan_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_type", SCANBATCHTYPE, nullable=False),
        sa.Column("status", SCANBATCHSTATUS, nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("source_import_batch_id", sa.Integer(), nullable=True),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("pending_tasks", sa.Integer(), nullable=False),
        sa.Column("running_tasks", sa.Integer(), nullable=False),
        sa.Column("success_tasks", sa.Integer(), nullable=False),
        sa.Column("failed_tasks", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_import_batch_id"], ["import_batches.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scan_batches_batch_type"), "scan_batches", ["batch_type"], unique=False
    )
    op.create_index(
        op.f("ix_scan_batches_cluster_id"), "scan_batches", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_scan_batches_source_import_batch_id"),
        "scan_batches",
        ["source_import_batch_id"],
        unique=True,
    )
    op.create_index(op.f("ix_scan_batches_status"), "scan_batches", ["status"], unique=False)
    op.create_foreign_key(
        "fk_import_batches_scan_batch_id_scan_batches",
        "import_batches",
        "scan_batches",
        ["scan_batch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "import_row_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("import_status", IMPORTSTATUS, nullable=False),
        sa.Column("import_message", sa.String(length=500), nullable=False),
        sa.Column("test_status", IMPORTTESTSTATUS, nullable=False),
        sa.Column("test_message", sa.String(length=500), nullable=True),
        sa.Column("test_worker_id", sa.String(length=36), nullable=True),
        sa.Column("test_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("test_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("test_attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_import_row_batch_number", "import_row_results", ["batch_id", "row_number"], unique=False
    )
    op.create_index(
        op.f("ix_import_row_results_test_lease_expires_at"),
        "import_row_results",
        ["test_lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_row_results_test_worker_id"),
        "import_row_results",
        ["test_worker_id"],
        unique=False,
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("trigger_type", SCANTRIGGER, nullable=False),
        sa.Column("status", SCANSTATUS, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connection_count", sa.Integer(), nullable=False),
        sa.Column("warning_message", sa.String(length=500), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scan_device_started", "scan_runs", ["device_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_scan_device_status_started",
        "scan_runs",
        ["device_id", "status", "started_at"],
        unique=False,
    )
    op.create_index(op.f("ix_scan_runs_status"), "scan_runs", ["status"], unique=False)
    op.create_table(
        "connection_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=8), nullable=False),
        sa.Column("address_family", sa.String(length=8), nullable=False),
        sa.Column("local_ip", sa.String(length=255), nullable=False),
        sa.Column("local_port", sa.Integer(), nullable=False),
        sa.Column("remote_ip", sa.String(length=255), nullable=True),
        sa.Column("remote_port", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("process_name", sa.String(length=255), nullable=True),
        sa.Column("remote_hostname", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["scan_run_id"], ["scan_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_connection_history_service",
        "connection_records",
        ["scan_run_id", "remote_ip", "remote_port", "protocol", "process_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connection_records_state"), "connection_records", ["state"], unique=False
    )
    op.create_index(
        "ix_connection_remote_scan",
        "connection_records",
        ["remote_ip", "scan_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_connection_scan_process",
        "connection_records",
        ["scan_run_id", "process_name"],
        unique=False,
    )
    op.create_index(
        "ix_connection_scan_protocol",
        "connection_records",
        ["scan_run_id", "protocol"],
        unique=False,
    )
    op.create_index(
        "ix_connection_scan_remote",
        "connection_records",
        ["scan_run_id", "remote_ip"],
        unique=False,
    )
    op.create_table(
        "scan_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("trigger_type", SCANTRIGGER, nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", SCANTASKSTATUS, nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=36), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_run_id"], ["scan_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scan_tasks_claim", "scan_tasks", ["status", "priority", "created_at"], unique=False
    )
    op.create_index(op.f("ix_scan_tasks_device_id"), "scan_tasks", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_scan_tasks_lease_expires_at"), "scan_tasks", ["lease_expires_at"], unique=False
    )
    op.create_index(op.f("ix_scan_tasks_priority"), "scan_tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_scan_tasks_scan_run_id"), "scan_tasks", ["scan_run_id"], unique=False)
    op.create_index(op.f("ix_scan_tasks_status"), "scan_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_scan_tasks_worker_id"), "scan_tasks", ["worker_id"], unique=False)
    op.create_index(
        "uq_scan_tasks_device_active",
        "scan_tasks",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.create_table(
        "scan_batch_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("status", SCANTASKSTATUS, nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["scan_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["scan_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "device_id", name="uq_scan_batch_device"),
    )
    op.create_index(
        op.f("ix_scan_batch_items_batch_id"), "scan_batch_items", ["batch_id"], unique=False
    )
    op.create_index(
        "ix_scan_batch_items_batch_status", "scan_batch_items", ["batch_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_scan_batch_items_device_id"), "scan_batch_items", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_scan_batch_items_status"), "scan_batch_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_scan_batch_items_task_id"), "scan_batch_items", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scan_batch_items_task_id"), table_name="scan_batch_items")
    op.drop_index(op.f("ix_scan_batch_items_status"), table_name="scan_batch_items")
    op.drop_index(op.f("ix_scan_batch_items_device_id"), table_name="scan_batch_items")
    op.drop_index("ix_scan_batch_items_batch_status", table_name="scan_batch_items")
    op.drop_index(op.f("ix_scan_batch_items_batch_id"), table_name="scan_batch_items")
    op.drop_table("scan_batch_items")
    op.drop_index(
        "uq_scan_tasks_device_active",
        table_name="scan_tasks",
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.drop_index(op.f("ix_scan_tasks_worker_id"), table_name="scan_tasks")
    op.drop_index(op.f("ix_scan_tasks_status"), table_name="scan_tasks")
    op.drop_index(op.f("ix_scan_tasks_scan_run_id"), table_name="scan_tasks")
    op.drop_index(op.f("ix_scan_tasks_priority"), table_name="scan_tasks")
    op.drop_index(op.f("ix_scan_tasks_lease_expires_at"), table_name="scan_tasks")
    op.drop_index(op.f("ix_scan_tasks_device_id"), table_name="scan_tasks")
    op.drop_index("ix_scan_tasks_claim", table_name="scan_tasks")
    op.drop_table("scan_tasks")
    op.drop_index("ix_connection_scan_remote", table_name="connection_records")
    op.drop_index("ix_connection_scan_protocol", table_name="connection_records")
    op.drop_index("ix_connection_scan_process", table_name="connection_records")
    op.drop_index("ix_connection_remote_scan", table_name="connection_records")
    op.drop_index(op.f("ix_connection_records_state"), table_name="connection_records")
    op.drop_index("ix_connection_history_service", table_name="connection_records")
    op.drop_table("connection_records")
    op.drop_index(op.f("ix_scan_runs_status"), table_name="scan_runs")
    op.drop_index("ix_scan_device_status_started", table_name="scan_runs")
    op.drop_index("ix_scan_device_started", table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_index(op.f("ix_import_row_results_test_worker_id"), table_name="import_row_results")
    op.drop_index(
        op.f("ix_import_row_results_test_lease_expires_at"), table_name="import_row_results"
    )
    op.drop_index("ix_import_row_batch_number", table_name="import_row_results")
    op.drop_table("import_row_results")
    op.drop_index(op.f("ix_scan_batches_status"), table_name="scan_batches")
    op.drop_index(op.f("ix_scan_batches_source_import_batch_id"), table_name="scan_batches")
    op.drop_index(op.f("ix_scan_batches_cluster_id"), table_name="scan_batches")
    op.drop_index(op.f("ix_scan_batches_batch_type"), table_name="scan_batches")
    op.drop_constraint(
        "fk_import_batches_scan_batch_id_scan_batches",
        "import_batches",
        type_="foreignkey",
    )
    op.drop_table("scan_batches")
    op.drop_index(op.f("ix_devices_cluster_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(
        op.f("ix_cluster_internal_networks_cluster_id"), table_name="cluster_internal_networks"
    )
    op.drop_table("cluster_internal_networks")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_import_batches_status"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_scan_batch_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_clusters_name"), table_name="clusters")
    op.drop_table("clusters")
    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
